#!/bin/bash
TEXFILENAME="$1"
FILE="${TEXFILENAME%.*}"
rm -rf ${FILE}.out ${FILE}.aux ${FILE}.bbl ${FILE}.blg ${FILE}.log ${FILE}Notes.bib ${FILE}.toc
export TEXINPUTS=.//:$TEXINPUTS
pdflatex ${FILE}.tex
pdflatex ${FILE}.tex
rm -rf ${FILE}.out ${FILE}.aux ${FILE}.bbl ${FILE}.blg ${FILE}.log ${FILE}Notes.bib ${FILE}.toc
